// GENERATED by `pnpm gen:cli-docs` from crates/safu-node — do not edit by hand.
// It mirrors the CLI's own help; change the CLI, then regenerate.
import type { CliSpec } from './spec.js';

export const cliSpec: CliSpec = {
  binary: 'safu-node',
  version: '0.1.0',
  tagline: 'safu-node — headless zero-knowledge backup node',
  usage: 'safu-node <command> [options]',
  dataDirDefault: './safu-node-data',
  commands: [
    { name: 'init', arg: null, summary: "Create this node's identity and data dir" },
    { name: 'info', arg: null, summary: "Print this node's signing id, address, and pairing code" },
    {
      name: 'link',
      arg: '<code>',
      summary: 'Authorize a device (its connection code) and remember it',
    },
    {
      name: 'unlink',
      arg: '<signing-id>',
      summary: "Revoke a device's write access and stop backing it up",
    },
    { name: 'list', arg: null, summary: 'List linked devices' },
    { name: 'serve', arg: null, summary: 'Run the always-on backup node (Ctrl-C to stop)' },
    { name: 'version', arg: null, summary: 'Print the version' },
  ],
  options: [
    {
      flag: '--data-dir',
      value: '<path>',
      summary: 'Directory this node owns',
      env: 'SAFU_NODE_DATA_DIR',
      required: false,
      default: './safu-node-data',
    },
    {
      flag: '--passphrase',
      value: '<pass>',
      summary: "Derives this node's identity",
      env: 'SAFU_NODE_PASSPHRASE',
      required: true,
      default: null,
    },
  ],
};
