// GENERATED by `pnpm gen:cli-docs` from crates/sharu — do not edit by hand.
// It mirrors the CLI's own help; change the CLI, then regenerate.
import type { CliSpec } from './spec.js';

export const cliSpec: CliSpec = {
  binary: 'sharu',
  version: '0.0.5',
  tagline: 'sharu — headless zero-knowledge backup node & public-share host',
  usage: 'sharu <command> [options]',
  dataDirDefault: './sharu-data',
  commands: [
    {
      name: 'init',
      arg: null,
      summary: "Create this node's identity and data dir",
    },
    {
      name: 'info',
      arg: null,
      summary: "Print this node's signing id, address, and pairing code",
    },
    {
      name: 'link',
      arg: '<code>',
      summary: 'Authorize a device (its connection code) and remember it',
    },
    {
      name: 'unlink',
      arg: '<signing-id>',
      summary: "Revoke a device's write access and stop backing it up",
    },
    {
      name: 'list',
      arg: null,
      summary: 'List linked devices and their safety numbers',
    },
    {
      name: 'files',
      arg: null,
      summary: "List the files held in this node's backup replica",
    },
    {
      name: 'status',
      arg: null,
      summary: 'Print a snapshot: files, blocks held, share pins, devices',
    },
    {
      name: 'tui',
      arg: null,
      summary: 'Live full-screen dashboard of the node (refreshes; q to quit)',
    },
    {
      name: 'reset',
      arg: null,
      summary: 'Delete all node data (identity, devices, blocks) and start over',
    },
    {
      name: 'serve',
      arg: null,
      summary: 'Run the node; first run on a terminal guides pairing (Ctrl-C to stop)',
    },
    {
      name: 'update',
      arg: null,
      summary: 'Check for a newer release (use --apply to install it)',
    },
    {
      name: 'version',
      arg: null,
      summary: 'Print the version',
    },
  ],
  options: [
    {
      flag: '--data-dir',
      value: '<path>',
      summary: 'Directory this node owns',
      env: 'SHARU_DATA_DIR',
      required: false,
      default: './sharu-data',
    },
    {
      flag: '--passphrase',
      value: '<pass>',
      summary: "Derives this node's identity",
      env: 'SHARU_PASSPHRASE',
      required: true,
      default: null,
    },
  ],
};
